# Generated by Django 6.0.5 on 2026-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bebidas', 'Bebidas'), ('lacteos', 'Lácteos'), ('golosinas', 'Golosinas'), ('snacks', 'Snacks'), ('bolleria', 'Bollería'), ('no_comestibles', 'No comestibles'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
