# Generated by Django 6.0.5 on 2026-05-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_machine',
            field=models.CharField(choices=[('vending', 'Vending Machine'), ('coffee', 'Coffee Machine'), ('snack', 'Snack Machine'), ('other', 'Other')], default='coffee', max_length=20),
        ),
    ]
