# Generated by Django 6.0.5 on 2026-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('cafe', 'Café'), ('lacteos', 'Lácteos'), ('golosinas', 'Golosinas'), ('snacks', 'Snacks'), ('bolleria', 'Bollería'), ('no_comestibles', 'No comestibles'), ('otros', 'Otros')], default='cafe', max_length=50),
        ),
    ]
