# Generated by Django 6.0.5 on 2026-05-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='serie_number',
        ),
    ]
