# Generated by Django 6.0.5 on 2026-06-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0002_remove_machine_serie_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineSupplyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_inventory', to='machines.machine')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_inventory', to='supplies.supply')),
            ],
            options={
                'verbose_name': 'Machine Supply Inventory',
                'verbose_name_plural': 'Machine Supply Inventories',
                'unique_together': {('machine', 'supply')},
            },
        ),
    ]
