# Generated by Django 6.0.5 on 2026-06-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_supply_cost_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='cost_per_unit',
            new_name='cost',
        ),
    ]
